### ISSUE TITLE
请问同步异步影响收发消息吗？

### ISSUE THREAD

**Issue by TownTowner** [Coldairarrow/DotNettySocket#3]
是这样的，我用代码给出的TCP server和client样例测试收发消息正常，然后我改造为同步的控制台收发也正常，但是不用代码框架而用原生的同步socket代码请求改造为同步控制台
【
            var result = theServer.Result;
】
的框架样例，新链接可以触发方法，但是却收不到消息，请问是哪里的原因呢？

为什么没有build的方法？

**Comment by Coldairarrow** [comment]
原生使用问题自己研究
